AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - 'config/**/*'
  DisplayCopNames: true
# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 成形のためにシングルスペースの有無
SingleBeforeFirstArg:
  Enabled: false

# トップレベルにあるコメントの有無
Style/Documentation:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

StringLiterals:
  Enabled: false
FormatString:
  EnforcedStyle: percent

# 行が長すぎる
Metrics/LineLength:
  Enabled: false

# メソッドの行数が多すぎる
Metrics/MethodLength:
  CountComments: false
  Max: 30
Metrics/AbcSize:
  Enabled: false

# ネストが深すぎる
BlockNesting:
  Max: 5

# クラスの行数が多すぎる
ClassLength:
  Enabled: false

# 循環的複雑度が高すぎる(ifやforなどを1メソッド内で使いすぎている)
CyclomaticComplexity:
  Enabled: false

# 例外を抑制している
HandleExceptions:
  Enabled: false

# 引数の数が多すぎる
ParameterLists:
  Max: 12
